---
deployment:
  tasks:


    - export DEPLOYPATH=/home/ecobricks/public_html/


    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp -R banners $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp stylesheet-1-1.css $DEPLOYPATH
    - /bin/cp accordion-scripts.js $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    - /bin/cp arc.php $DEPLOYPATH
    - /bin/cp catalyst.php $DEPLOYPATH
    - /bin/cp what.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp coefficients.php $DEPLOYPATH
    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp brikchain.php $DEPLOYPATH 
    - /bin/cp 2021-regenreport.php $DEPLOYPATH
    - /bin/cp sequest.php $DEPLOYPATH

  
    - export DEPLOYPATH=/home/ecobricks/public_html/en/


    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp -R banners $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp stylesheet-1-1.css $DEPLOYPATH
    - /bin/cp accordion-scripts.js $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    - /bin/cp arc.php $DEPLOYPATH
    - /bin/cp catalyst.php $DEPLOYPATH
    - /bin/cp what.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp coefficients.php $DEPLOYPATH
    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp brikchain.php $DEPLOYPATH 
    - /bin/cp 2021-regenreport.php $DEPLOYPATH
    - /bin/cp sequest.php $DEPLOYPATH



    - export DEPLOYPATH=/home/ecobricks/public_html/es/


    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp -R banners $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp stylesheet-1-1.css $DEPLOYPATH
    - /bin/cp accordion-scripts.js $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    - /bin/cp arc.php $DEPLOYPATH
    - /bin/cp catalyst.php $DEPLOYPATH
    - /bin/cp what.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp coefficients.php $DEPLOYPATH
    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp brikchain.php $DEPLOYPATH 
    - /bin/cp 2021-regenreport.php $DEPLOYPATH
    - /bin/cp sequest.php $DEPLOYPATH



    - export DEPLOYPATH=/home/ecobricks/public_html/id/


    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp -R banners $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp stylesheet-1-1.css $DEPLOYPATH
    - /bin/cp accordion-scripts.js $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    - /bin/cp arc.php $DEPLOYPATH
    - /bin/cp catalyst.php $DEPLOYPATH
    - /bin/cp what.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp coefficients.php $DEPLOYPATH
    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp brikchain.php $DEPLOYPATH 
    - /bin/cp 2021-regenreport.php $DEPLOYPATH
    - /bin/cp sequest.php $DEPLOYPATH