---
deployment:
  tasks:


    - export DEPLOYPATH=/home/ecobricks/public_html/en/


    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp -R banners $DEPLOYPATH
    - /bin/cp -R menus $DEPLOYPATH
    - /bin/cp -R footers $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp sitemap-multilingual.xml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp accordion-scripts.js $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH
    - /bin/cp ssp.class.php $DEPLOYPATH
    - /bin/cp ajax-ecobricks.php $DEPLOYPATH
    - /bin/cp ajax-cash-trans.php $DEPLOYPATH
    - /bin/cp ajax-brk-trans.php $DEPLOYPATH
    - /bin/cp details-ecobrick.php $DEPLOYPATH
    - /bin/cp details-cash-trans.php $DEPLOYPATH
    - /bin/cp details-brk-trans.php $DEPLOYPATH

    - /bin/cp stylesheet-general.css $DEPLOYPATH
    - /bin/cp styles-landing.php $DEPLOYPATH
    - /bin/cp stylesheet-first-load.css $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    - /bin/cp arc.php $DEPLOYPATH
    - /bin/cp catalyst.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp coefficients.php $DEPLOYPATH
    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp 2021-regenreport.php $DEPLOYPATH
    - /bin/cp sequest.php $DEPLOYPATH
    - /bin/cp transition.php $DEPLOYPATH
    - /bin/cp build.php $DEPLOYPATH
    - /bin/cp media.php $DEPLOYPATH
    - /bin/cp brikcoins.php $DEPLOYPATH
    - /bin/cp drop-off.php $DEPLOYPATH



    - export DEPLOYPATH=/home/ecobricks/public_html/es/


    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp -R banners $DEPLOYPATH
    - /bin/cp -R menus $DEPLOYPATH
    - /bin/cp -R footers $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp sitemap-multilingual.xml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp accordion-scripts.js $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH
    - /bin/cp ssp.class.php $DEPLOYPATH
    - /bin/cp ajax-ecobricks.php $DEPLOYPATH
    - /bin/cp ajax-cash-trans.php $DEPLOYPATH
    - /bin/cp ajax-brk-trans.php $DEPLOYPATH
    - /bin/cp details-ecobrick.php $DEPLOYPATH
    - /bin/cp details-cash-trans.php $DEPLOYPATH
    - /bin/cp details-brk-trans.php $DEPLOYPATH

    - /bin/cp stylesheet-general.css $DEPLOYPATH
    - /bin/cp styles-landing.php $DEPLOYPATH
    - /bin/cp stylesheet-first-load.css $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    - /bin/cp arc.php $DEPLOYPATH
    - /bin/cp catalyst.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp coefficients.php $DEPLOYPATH
    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp 2021-regenreport.php $DEPLOYPATH
    - /bin/cp sequest.php $DEPLOYPATH
    - /bin/cp transition.php $DEPLOYPATH
    - /bin/cp build.php $DEPLOYPATH
    - /bin/cp media.php $DEPLOYPATH
    - /bin/cp brikcoins.php $DEPLOYPATH
    - /bin/cp drop-off.php $DEPLOYPATH



    - export DEPLOYPATH=/home/ecobricks/public_html/id/


    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp -R banners $DEPLOYPATH
    - /bin/cp -R menus $DEPLOYPATH
    - /bin/cp -R footers $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp sitemap-multilingual.xml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp accordion-scripts.js $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH
    - /bin/cp ssp.class.php $DEPLOYPATH
    - /bin/cp ajax-ecobricks.php $DEPLOYPATH
    - /bin/cp ajax-cash-trans.php $DEPLOYPATH
    - /bin/cp ajax-brk-trans.php $DEPLOYPATH
    - /bin/cp details-ecobrick.php $DEPLOYPATH
    - /bin/cp details-cash-trans.php $DEPLOYPATH
    - /bin/cp details-brk-trans.php $DEPLOYPATH

    - /bin/cp stylesheet-general.css $DEPLOYPATH
    - /bin/cp styles-landing.php $DEPLOYPATH
    - /bin/cp stylesheet-first-load.css $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    - /bin/cp arc.php $DEPLOYPATH
    - /bin/cp catalyst.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp coefficients.php $DEPLOYPATH
    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp 2021-regenreport.php $DEPLOYPATH
    - /bin/cp sequest.php $DEPLOYPATH
    - /bin/cp transition.php $DEPLOYPATH
    - /bin/cp build.php $DEPLOYPATH
    - /bin/cp media.php $DEPLOYPATH
    - /bin/cp brikcoins.php $DEPLOYPATH
    - /bin/cp drop-off.php $DEPLOYPATH







    - export DEPLOYPATH=/home/ecobricks/public_html/


    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp -R banners $DEPLOYPATH
    - /bin/cp -R menus $DEPLOYPATH
    - /bin/cp -R footers $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH

    - /bin/cp -R en $DEPLOYPATH
    - /bin/cp -R id $DEPLOYPATH
    - /bin/cp -R es $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp sitemap-multilingual.xml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp accordion-scripts.js $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH
    - /bin/cp ssp.class.php $DEPLOYPATH

    - /bin/cp ajax-ecobricks.php $DEPLOYPATH
    - /bin/cp ajax-cash-trans.php $DEPLOYPATH
    - /bin/cp ajax-brk-trans.php $DEPLOYPATH
    - /bin/cp details-ecobrick.php $DEPLOYPATH
    - /bin/cp details-cash-trans.php $DEPLOYPATH
    - /bin/cp details-brk-trans.php $DEPLOYPATH

    - /bin/cp stylesheet-general.css $DEPLOYPATH
    - /bin/cp styles-landing.php $DEPLOYPATH
    - /bin/cp stylesheet-first-load.css $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    - /bin/cp arc.php $DEPLOYPATH
    - /bin/cp catalyst.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp coefficients.php $DEPLOYPATH
    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH

    - /bin/cp 2021-regenreport.php $DEPLOYPATH
    - /bin/cp sequest.php $DEPLOYPATH
    - /bin/cp transition.php $DEPLOYPATH
    - /bin/cp build.php $DEPLOYPATH
    - /bin/cp media.php $DEPLOYPATH
    - /bin/cp brikcoins.php $DEPLOYPATH
    - /bin/cp drop-off.php $DEPLOYPATH
    - /bin/cp principles.php $DEPLOYPATH

