---
deployment:
  tasks:


    - export DEPLOYPATH=/home/ecobricks/public_html/

    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH

    - /bin/cp stylesheet-1-1.css $DEPLOYPATH
    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH
    



    - export DEPLOYPATH=/home/ecobricks/public_html/en/

    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp stylesheet-1-1.css $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH



    - export DEPLOYPATH=/home/ecobricks/public_html/es/

    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp stylesheet-1-1.css $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH



    - export DEPLOYPATH=/home/ecobricks/public_html/id/

    - /bin/cp gea-webhead.html $DEPLOYPATH
    - /bin/cp faqs.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
    - /bin/cp -R photos $DEPLOYPATH

    - /bin/cp welcome.php $DEPLOYPATH
    - /bin/cp stylesheet-1-1.css $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp menu-bar.php $DEPLOYPATH



   