---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ecobricks/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp stylesheet.css $DEPLOYPATH
    - /bin/cp stylesheet2.css $DEPLOYPATH
    - /bin/cp faqs.html $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R pngs $DEPLOYPATH
